### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by toddsundsted** [comment]
@tvdijen have you run the tests? on both linux and osx I am getting crashes. I'm investigating, but on osx it looks like some of the `sprintf()` arguments may need to be changed from `%d` to `%u`. the other changes that might be risky and should be tested are changes to the crypto functions.

**Comment by toddsundsted** [comment]
in the other PR, you asked about the code inside the `#if 0` blocks. that's a great solution to keeping it out of the compile path.

**Comment by tvdijen** [comment]
Haven't ran the tests, I'll do that tonight.. I did fire up a LambdaCore with it and executed some random verbs and it ran fine... The %d/%u makes sense, I'll fix that

**Comment by tvdijen** [comment]
I'm having trouble running the tests..

> for test in test/*.rb ; do \
>   echo "\n\nRunning $test..." ; \
>   ruby -rubygems -Itest/lib $test ; \
> done
> \n\nRunning test/test_algorithms.rb...
> Loaded suite test/test_algorithms
> Started
> > connect programmer
> > ; return string_hmac("what do ya want for nothing?", "Jefe", "sha1");

And then nothing happens until the connection times out.. Am I missing something here?

**Comment by toddsundsted** [comment]
it sounds like it cannot connect to the test server. do you have a server running the test database, as well? there is some documentation in https://github.com/toddsundsted/stunt/blob/master/README.tests (the Ruby version needs to be updated, but otherwise the documentation should be good).

**Comment by tvdijen** [comment]
Yes, that's the doc I've followed... It does connect, because I can see a new incoming connection

**Comment by tvdijen** [comment]
Nevermind, I think I accidentally took the wrong database.. I tend to dump to Test.db when testing new code.. Redownloaded it and now the tests run

**Comment by tvdijen** [comment]
Tests run 100% OK now

**Comment by tvdijen** [comment]
Hey Todd!  Any chance of getting this and the other PR's merged?

**Pull request closed without merging**
