### PR TITLE
Provide the server process-id to the MOO

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by toddsundsted** [comment]
Have you considered making making this a [wizardly] builtin function instead of a property on the system object?

The advantage of a builtin is it does not imply the value is writeable/changeable, whereas properties are. The change would require roughly the same amount of code and would fit nicely in `server.cc`.

**Comment by tvdijen** [comment]
Hmm, yeah that's probably a better idea... I wonder why I didn't come up with that!

**Comment by toddsundsted** [comment]
This looks great! To keep the history clean, can you rewrite these three commits into a single commit and I will merge into into the master branch. Thank you!

**Comment by toddsundsted** [comment]
And update to the documentation would be awesome, as well, but I handle that part.

**Comment by tvdijen** [comment]
I don't think that's possible with the online GUI here on Github.. The only way I can think of is to create a new pull-request based on the last commit..

**Comment by toddsundsted** [comment]
You'd have to rewrite your git commit history and then force push to the branch, but I'm fine with you closing this PR and opening another on another branch. Thanks!

**Comment by tvdijen** [comment]
Note to self; learn more about git... For now, the change is in #6

**Pull request closed without merging**
