### PR TITLE
Implementation of TYPE_INSTANCE wildcard-type

### PR DESCRIPTION
**Pull request by tvdijen**
Implementation of TYPE_INSTANCE wildcard-type for TYPE_OBJ and TYPE_ANON

### CODE REVIEW

**Comment by toddsundsted** [comment]
I ran the tests on this branch, and it looks like the patch allows anonymous objects to be passed in to the `is_player()` and possibly the `set_player_flag()` builtins. I didn't see any other failures.

**Comment by tvdijen** [comment]
is_player() does indeed allow anonymous objects, but it will always unconditionally return 0. It saves lot's of  type-checking in MOO-code, so it makes sense.
The set_player_flag() is a mistake, I'll fix that.

**Comment by tvdijen** [comment]
Tests run 100% OK

**Comment by toddsundsted** [comment]
you are correct about `set_player_flag()`. I reran my tests and it raises `E_TYPE`. that was my mistake.

returning `0` rather than raising an error is a big change to the behavior of `is_player()` and I don't see the benefit to the change. existing code that depends on it raising `E_TYPE` will silently fail unless it is changed to check the return code. the standard behavior of builtins is to raise `E_TYPE` if an incorrect type is specified. this is the case even for numeric types. `floor()` will raise `E_TYPE` if passed an integer instead of a float.

**Comment by tvdijen** [comment]
I'd argue that we'd like to mimic `OBJ`'s as much as possible when we're using `ANON`'s, so having `is_player()` deal with `ANON`'s isn't that crazy.. LambdaCore horribly breaks when you feed verbs like $root_class:set_name, :initialize or :recycle with an `ANON`...

**Pull request closed without merging**
