### PR TITLE
Suppress lots of compiler warnings

### PR DESCRIPTION
**Pull request by tvdijen**
Mostly unsigned/signed int warnings and unused vars/code

### CODE REVIEW

**Comment by toddsundsted** [comment]
@tvdijen I needed to rewrite the master branch to fix up bad commit information. that broke this PR because github doesn't deal will with changes like that and PRs. very sorry about this. you should be able to rebase your changes on top of my current master and everything will be fine. I verified that on a branch of my own just to be sure: https://github.com/toddsundsted/stunt/commits/patch-2

also, it looks like in commit 139404e you added a preprocessor check around `gc_stats()`. the warning is due to `gc_debug()` and not `gc_stats()`.

**Comment by toddsundsted** [comment]
I haven't tried to compile on linux, but on llvm-g++ on OSX, linking fails because the linker can't find `read_rt_env(char const***, Var**, unsigned int*)`. I think the signature of this function needs to be changed to match the call to this function in execute.cc.

**Comment by tvdijen** [comment]
Hey Todd, no problem.. I'll redo the work when I have some time, taking into account the comments you've made.

Now we're at it, perhaps you can take a look at the parts where I've added `#IF 0`... Those are unused functions but I didn't want to throw them away... You have any future use for those?

**Comment by tvdijen** [comment]
And what about the other two PR's? Do I have to redo those as well after your rewrite of master?

**Comment by tvdijen** [comment]
See PR #12

**Pull request closed without merging**
