### PR TITLE
Implementation of TYPE_INSTANCE wildcard-type for TYPE_OBJ and TYPE_ANON

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by tvdijen** [comment]
One question that came up when looking at all the builtins in objects.cc was:
Shouldn't the second argument of bf_isa not be TYPE_OBJ? It's impossible to make children of anonymous objects, right??

**Comment by toddsundsted** [comment]
it's currently impossible to create children of anonymous objects. allowing both "object" and "parent" here to be instances (object or anonymous) is maybe too liberal, however, the ultimate call to `db_object_isa()` accounts for this and gives the correct answer. before changing this we'd need to make sure no moo-code depends on this not throwing an error.

**Comment by tvdijen** [comment]
So, if I understand you correctly, you agree that the original TYPE_ANY for the second argument is stupid, but TYPE_OBJ (as per my change) is too strict and should ultimately be TYPE_INSTANCE as long as db_object_isa() can handle this?

**Comment by toddsundsted** [comment]
`TYPE_ANY` was okay because the builtin checked the type itself (and raised `E_TYPE` if necessary). if you change the `register_function()` call to specify `TYPE_INSTANCE` instead of `TYPE_ANY` you can do away with the explicit checks in `bf_isa()`.

**Comment by tvdijen** [comment]
Okay, so I've done a little testing today and smashed two issues... Tests with both Improvise and LambdaCore have gone pretty well;  I have not been able to produce any errors!

**Comment by tvdijen** [comment]
See PR #13

**Pull request closed without merging**
